// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyML38nGqnniUFM8ye9BdW_Hi-BfEEP00',
    appId: '1:178483796000:web:89a14575d6edb9e7e24445',
    messagingSenderId: '178483796000',
    projectId: 'fimetrack-d53b8',
    authDomain: 'fimetrack-d53b8.firebaseapp.com',
    storageBucket: 'fimetrack-d53b8.firebasestorage.app',
    measurementId: 'G-L4DKV0067L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChfVvQGdl-06_nOlSoSmAJUNr3TZD10Zk',
    appId: '1:178483796000:android:d2bdc2cab2600be6e24445',
    messagingSenderId: '178483796000',
    projectId: 'fimetrack-d53b8',
    storageBucket: 'fimetrack-d53b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzJx89VfWi5svlxH4BwgRKAvRbW2kohsA',
    appId: '1:178483796000:ios:94990d67c8e4f022e24445',
    messagingSenderId: '178483796000',
    projectId: 'fimetrack-d53b8',
    storageBucket: 'fimetrack-d53b8.firebasestorage.app',
    iosBundleId: 'com.ajinasywa.fimetrack2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzJx89VfWi5svlxH4BwgRKAvRbW2kohsA',
    appId: '1:178483796000:ios:ec6f1f1170209f25e24445',
    messagingSenderId: '178483796000',
    projectId: 'fimetrack-d53b8',
    storageBucket: 'fimetrack-d53b8.firebasestorage.app',
    iosBundleId: 'com.example.fimetrack2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyML38nGqnniUFM8ye9BdW_Hi-BfEEP00',
    appId: '1:178483796000:web:f731c90a7d1becd3e24445',
    messagingSenderId: '178483796000',
    projectId: 'fimetrack-d53b8',
    authDomain: 'fimetrack-d53b8.firebaseapp.com',
    storageBucket: 'fimetrack-d53b8.firebasestorage.app',
    measurementId: 'G-17651WFXSK',
  );
}
